//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e9)
//
// On Fri Mar 13 14:26:05 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_dataPorts_0_putData        O     1
// dataPorts_0_getData            O    16
// RDY_dataPorts_0_getData        O     1
// RDY_dataPorts_1_putData        O     1
// dataPorts_1_getData            O    16
// RDY_dataPorts_1_getData        O     1
// RDY_dataPorts_2_putData        O     1
// dataPorts_2_getData            O    16
// RDY_dataPorts_2_getData        O     1
// RDY_dataPorts_3_putData        O     1
// dataPorts_3_getData            O    16
// RDY_dataPorts_3_getData        O     1
// RDY_dataPorts_4_putData        O     1
// dataPorts_4_getData            O    16
// RDY_dataPorts_4_getData        O     1
// RDY_dataPorts_5_putData        O     1
// dataPorts_5_getData            O    16
// RDY_dataPorts_5_getData        O     1
// RDY_dataPorts_6_putData        O     1
// dataPorts_6_getData            O    16
// RDY_dataPorts_6_getData        O     1
// RDY_dataPorts_7_putData        O     1
// dataPorts_7_getData            O    16
// RDY_dataPorts_7_getData        O     1
// RDY_controlPorts_putConfig     O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// dataPorts_0_putData_data       I    16 reg
// dataPorts_1_putData_data       I    16 reg
// dataPorts_2_putData_data       I    16 reg
// dataPorts_3_putData_data       I    16 reg
// dataPorts_4_putData_data       I    16 reg
// dataPorts_5_putData_data       I    16 reg
// dataPorts_6_putData_data       I    16 reg
// dataPorts_7_putData_data       I    16 reg
// controlPorts_putConfig_newConfig  I   160
// controlPorts_putConfig_numActualActiveMultSwitches  I    32
// EN_dataPorts_0_putData         I     1
// EN_dataPorts_1_putData         I     1
// EN_dataPorts_2_putData         I     1
// EN_dataPorts_3_putData         I     1
// EN_dataPorts_4_putData         I     1
// EN_dataPorts_5_putData         I     1
// EN_dataPorts_6_putData         I     1
// EN_dataPorts_7_putData         I     1
// EN_controlPorts_putConfig      I     1
// EN_dataPorts_0_getData         I     1
// EN_dataPorts_1_getData         I     1
// EN_dataPorts_2_getData         I     1
// EN_dataPorts_3_getData         I     1
// EN_dataPorts_4_getData         I     1
// EN_dataPorts_5_getData         I     1
// EN_dataPorts_6_getData         I     1
// EN_dataPorts_7_getData         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMN_MultiplierNetwork(CLK,
			      RST_N,

			      dataPorts_0_putData_data,
			      EN_dataPorts_0_putData,
			      RDY_dataPorts_0_putData,

			      EN_dataPorts_0_getData,
			      dataPorts_0_getData,
			      RDY_dataPorts_0_getData,

			      dataPorts_1_putData_data,
			      EN_dataPorts_1_putData,
			      RDY_dataPorts_1_putData,

			      EN_dataPorts_1_getData,
			      dataPorts_1_getData,
			      RDY_dataPorts_1_getData,

			      dataPorts_2_putData_data,
			      EN_dataPorts_2_putData,
			      RDY_dataPorts_2_putData,

			      EN_dataPorts_2_getData,
			      dataPorts_2_getData,
			      RDY_dataPorts_2_getData,

			      dataPorts_3_putData_data,
			      EN_dataPorts_3_putData,
			      RDY_dataPorts_3_putData,

			      EN_dataPorts_3_getData,
			      dataPorts_3_getData,
			      RDY_dataPorts_3_getData,

			      dataPorts_4_putData_data,
			      EN_dataPorts_4_putData,
			      RDY_dataPorts_4_putData,

			      EN_dataPorts_4_getData,
			      dataPorts_4_getData,
			      RDY_dataPorts_4_getData,

			      dataPorts_5_putData_data,
			      EN_dataPorts_5_putData,
			      RDY_dataPorts_5_putData,

			      EN_dataPorts_5_getData,
			      dataPorts_5_getData,
			      RDY_dataPorts_5_getData,

			      dataPorts_6_putData_data,
			      EN_dataPorts_6_putData,
			      RDY_dataPorts_6_putData,

			      EN_dataPorts_6_getData,
			      dataPorts_6_getData,
			      RDY_dataPorts_6_getData,

			      dataPorts_7_putData_data,
			      EN_dataPorts_7_putData,
			      RDY_dataPorts_7_putData,

			      EN_dataPorts_7_getData,
			      dataPorts_7_getData,
			      RDY_dataPorts_7_getData,

			      controlPorts_putConfig_newConfig,
			      controlPorts_putConfig_numActualActiveMultSwitches,
			      EN_controlPorts_putConfig,
			      RDY_controlPorts_putConfig);
  input  CLK;
  input  RST_N;

  // action method dataPorts_0_putData
  input  [15 : 0] dataPorts_0_putData_data;
  input  EN_dataPorts_0_putData;
  output RDY_dataPorts_0_putData;

  // actionvalue method dataPorts_0_getData
  input  EN_dataPorts_0_getData;
  output [15 : 0] dataPorts_0_getData;
  output RDY_dataPorts_0_getData;

  // action method dataPorts_1_putData
  input  [15 : 0] dataPorts_1_putData_data;
  input  EN_dataPorts_1_putData;
  output RDY_dataPorts_1_putData;

  // actionvalue method dataPorts_1_getData
  input  EN_dataPorts_1_getData;
  output [15 : 0] dataPorts_1_getData;
  output RDY_dataPorts_1_getData;

  // action method dataPorts_2_putData
  input  [15 : 0] dataPorts_2_putData_data;
  input  EN_dataPorts_2_putData;
  output RDY_dataPorts_2_putData;

  // actionvalue method dataPorts_2_getData
  input  EN_dataPorts_2_getData;
  output [15 : 0] dataPorts_2_getData;
  output RDY_dataPorts_2_getData;

  // action method dataPorts_3_putData
  input  [15 : 0] dataPorts_3_putData_data;
  input  EN_dataPorts_3_putData;
  output RDY_dataPorts_3_putData;

  // actionvalue method dataPorts_3_getData
  input  EN_dataPorts_3_getData;
  output [15 : 0] dataPorts_3_getData;
  output RDY_dataPorts_3_getData;

  // action method dataPorts_4_putData
  input  [15 : 0] dataPorts_4_putData_data;
  input  EN_dataPorts_4_putData;
  output RDY_dataPorts_4_putData;

  // actionvalue method dataPorts_4_getData
  input  EN_dataPorts_4_getData;
  output [15 : 0] dataPorts_4_getData;
  output RDY_dataPorts_4_getData;

  // action method dataPorts_5_putData
  input  [15 : 0] dataPorts_5_putData_data;
  input  EN_dataPorts_5_putData;
  output RDY_dataPorts_5_putData;

  // actionvalue method dataPorts_5_getData
  input  EN_dataPorts_5_getData;
  output [15 : 0] dataPorts_5_getData;
  output RDY_dataPorts_5_getData;

  // action method dataPorts_6_putData
  input  [15 : 0] dataPorts_6_putData_data;
  input  EN_dataPorts_6_putData;
  output RDY_dataPorts_6_putData;

  // actionvalue method dataPorts_6_getData
  input  EN_dataPorts_6_getData;
  output [15 : 0] dataPorts_6_getData;
  output RDY_dataPorts_6_getData;

  // action method dataPorts_7_putData
  input  [15 : 0] dataPorts_7_putData_data;
  input  EN_dataPorts_7_putData;
  output RDY_dataPorts_7_putData;

  // actionvalue method dataPorts_7_getData
  input  EN_dataPorts_7_getData;
  output [15 : 0] dataPorts_7_getData;
  output RDY_dataPorts_7_getData;

  // action method controlPorts_putConfig
  input  [159 : 0] controlPorts_putConfig_newConfig;
  input  [31 : 0] controlPorts_putConfig_numActualActiveMultSwitches;
  input  EN_controlPorts_putConfig;
  output RDY_controlPorts_putConfig;

  // signals for module outputs
  wire [15 : 0] dataPorts_0_getData,
		dataPorts_1_getData,
		dataPorts_2_getData,
		dataPorts_3_getData,
		dataPorts_4_getData,
		dataPorts_5_getData,
		dataPorts_6_getData,
		dataPorts_7_getData;
  wire RDY_controlPorts_putConfig,
       RDY_dataPorts_0_getData,
       RDY_dataPorts_0_putData,
       RDY_dataPorts_1_getData,
       RDY_dataPorts_1_putData,
       RDY_dataPorts_2_getData,
       RDY_dataPorts_2_putData,
       RDY_dataPorts_3_getData,
       RDY_dataPorts_3_putData,
       RDY_dataPorts_4_getData,
       RDY_dataPorts_4_putData,
       RDY_dataPorts_5_getData,
       RDY_dataPorts_5_putData,
       RDY_dataPorts_6_getData,
       RDY_dataPorts_6_putData,
       RDY_dataPorts_7_getData,
       RDY_dataPorts_7_putData;

  // ports of submodule multSwitches_0
  wire [19 : 0] multSwitches_0$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_0$dataPorts_getPSum,
		multSwitches_0$dataPorts_putIptData_newIptData;
  wire multSwitches_0$EN_controlPorts_putNewConfig,
       multSwitches_0$EN_dataPorts_getPSum,
       multSwitches_0$EN_dataPorts_putIptData,
       multSwitches_0$RDY_controlPorts_putNewConfig,
       multSwitches_0$RDY_dataPorts_getPSum,
       multSwitches_0$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_1
  wire [19 : 0] multSwitches_1$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_1$dataPorts_getPSum,
		multSwitches_1$dataPorts_putIptData_newIptData;
  wire multSwitches_1$EN_controlPorts_putNewConfig,
       multSwitches_1$EN_dataPorts_getPSum,
       multSwitches_1$EN_dataPorts_putIptData,
       multSwitches_1$RDY_controlPorts_putNewConfig,
       multSwitches_1$RDY_dataPorts_getPSum,
       multSwitches_1$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_2
  wire [19 : 0] multSwitches_2$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_2$dataPorts_getPSum,
		multSwitches_2$dataPorts_putIptData_newIptData;
  wire multSwitches_2$EN_controlPorts_putNewConfig,
       multSwitches_2$EN_dataPorts_getPSum,
       multSwitches_2$EN_dataPorts_putIptData,
       multSwitches_2$RDY_controlPorts_putNewConfig,
       multSwitches_2$RDY_dataPorts_getPSum,
       multSwitches_2$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_3
  wire [19 : 0] multSwitches_3$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_3$dataPorts_getPSum,
		multSwitches_3$dataPorts_putIptData_newIptData;
  wire multSwitches_3$EN_controlPorts_putNewConfig,
       multSwitches_3$EN_dataPorts_getPSum,
       multSwitches_3$EN_dataPorts_putIptData,
       multSwitches_3$RDY_controlPorts_putNewConfig,
       multSwitches_3$RDY_dataPorts_getPSum,
       multSwitches_3$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_4
  wire [19 : 0] multSwitches_4$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_4$dataPorts_getPSum,
		multSwitches_4$dataPorts_putIptData_newIptData;
  wire multSwitches_4$EN_controlPorts_putNewConfig,
       multSwitches_4$EN_dataPorts_getPSum,
       multSwitches_4$EN_dataPorts_putIptData,
       multSwitches_4$RDY_controlPorts_putNewConfig,
       multSwitches_4$RDY_dataPorts_getPSum,
       multSwitches_4$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_5
  wire [19 : 0] multSwitches_5$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_5$dataPorts_getPSum,
		multSwitches_5$dataPorts_putIptData_newIptData;
  wire multSwitches_5$EN_controlPorts_putNewConfig,
       multSwitches_5$EN_dataPorts_getPSum,
       multSwitches_5$EN_dataPorts_putIptData,
       multSwitches_5$RDY_controlPorts_putNewConfig,
       multSwitches_5$RDY_dataPorts_getPSum,
       multSwitches_5$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_6
  wire [19 : 0] multSwitches_6$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_6$dataPorts_getPSum,
		multSwitches_6$dataPorts_putIptData_newIptData;
  wire multSwitches_6$EN_controlPorts_putNewConfig,
       multSwitches_6$EN_dataPorts_getPSum,
       multSwitches_6$EN_dataPorts_putIptData,
       multSwitches_6$RDY_controlPorts_putNewConfig,
       multSwitches_6$RDY_dataPorts_getPSum,
       multSwitches_6$RDY_dataPorts_putIptData;

  // ports of submodule multSwitches_7
  wire [19 : 0] multSwitches_7$controlPorts_putNewConfig_newConfig;
  wire [15 : 0] multSwitches_7$dataPorts_getPSum,
		multSwitches_7$dataPorts_putIptData_newIptData;
  wire multSwitches_7$EN_controlPorts_putNewConfig,
       multSwitches_7$EN_dataPorts_getPSum,
       multSwitches_7$EN_dataPorts_putIptData,
       multSwitches_7$RDY_controlPorts_putNewConfig,
       multSwitches_7$RDY_dataPorts_getPSum,
       multSwitches_7$RDY_dataPorts_putIptData;

  // remaining internal signals
  wire multSwitches_2_RDY_controlPorts_putNewConfig___ETC___d38;

  // action method dataPorts_0_putData
  assign RDY_dataPorts_0_putData = multSwitches_0$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_0_getData
  assign dataPorts_0_getData = multSwitches_0$dataPorts_getPSum ;
  assign RDY_dataPorts_0_getData = multSwitches_0$RDY_dataPorts_getPSum ;

  // action method dataPorts_1_putData
  assign RDY_dataPorts_1_putData = multSwitches_1$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_1_getData
  assign dataPorts_1_getData = multSwitches_1$dataPorts_getPSum ;
  assign RDY_dataPorts_1_getData = multSwitches_1$RDY_dataPorts_getPSum ;

  // action method dataPorts_2_putData
  assign RDY_dataPorts_2_putData = multSwitches_2$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_2_getData
  assign dataPorts_2_getData = multSwitches_2$dataPorts_getPSum ;
  assign RDY_dataPorts_2_getData = multSwitches_2$RDY_dataPorts_getPSum ;

  // action method dataPorts_3_putData
  assign RDY_dataPorts_3_putData = multSwitches_3$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_3_getData
  assign dataPorts_3_getData = multSwitches_3$dataPorts_getPSum ;
  assign RDY_dataPorts_3_getData = multSwitches_3$RDY_dataPorts_getPSum ;

  // action method dataPorts_4_putData
  assign RDY_dataPorts_4_putData = multSwitches_4$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_4_getData
  assign dataPorts_4_getData = multSwitches_4$dataPorts_getPSum ;
  assign RDY_dataPorts_4_getData = multSwitches_4$RDY_dataPorts_getPSum ;

  // action method dataPorts_5_putData
  assign RDY_dataPorts_5_putData = multSwitches_5$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_5_getData
  assign dataPorts_5_getData = multSwitches_5$dataPorts_getPSum ;
  assign RDY_dataPorts_5_getData = multSwitches_5$RDY_dataPorts_getPSum ;

  // action method dataPorts_6_putData
  assign RDY_dataPorts_6_putData = multSwitches_6$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_6_getData
  assign dataPorts_6_getData = multSwitches_6$dataPorts_getPSum ;
  assign RDY_dataPorts_6_getData = multSwitches_6$RDY_dataPorts_getPSum ;

  // action method dataPorts_7_putData
  assign RDY_dataPorts_7_putData = multSwitches_7$RDY_dataPorts_putIptData ;

  // actionvalue method dataPorts_7_getData
  assign dataPorts_7_getData = multSwitches_7$dataPorts_getPSum ;
  assign RDY_dataPorts_7_getData = multSwitches_7$RDY_dataPorts_getPSum ;

  // action method controlPorts_putConfig
  assign RDY_controlPorts_putConfig =
	     multSwitches_1$RDY_controlPorts_putNewConfig &&
	     multSwitches_2_RDY_controlPorts_putNewConfig___ETC___d38 ;

  // submodule multSwitches_0
  mkMN_MultiplierSwitch multSwitches_0(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_0$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_0$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_0$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_0$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_0$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_0$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_0$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_0$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_0$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_1
  mkMN_MultiplierSwitch multSwitches_1(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_1$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_1$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_1$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_1$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_1$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_1$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_1$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_1$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_1$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_2
  mkMN_MultiplierSwitch multSwitches_2(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_2$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_2$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_2$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_2$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_2$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_2$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_2$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_2$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_2$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_3
  mkMN_MultiplierSwitch multSwitches_3(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_3$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_3$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_3$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_3$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_3$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_3$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_3$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_3$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_3$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_4
  mkMN_MultiplierSwitch multSwitches_4(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_4$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_4$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_4$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_4$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_4$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_4$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_4$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_4$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_4$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_5
  mkMN_MultiplierSwitch multSwitches_5(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_5$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_5$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_5$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_5$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_5$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_5$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_5$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_5$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_5$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_6
  mkMN_MultiplierSwitch multSwitches_6(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_6$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_6$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_6$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_6$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_6$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_6$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_6$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_6$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_6$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_7
  mkMN_MultiplierSwitch multSwitches_7(.CLK(CLK),
				       .RST_N(RST_N),
				       .controlPorts_putNewConfig_newConfig(multSwitches_7$controlPorts_putNewConfig_newConfig),
				       .dataPorts_putIptData_newIptData(multSwitches_7$dataPorts_putIptData_newIptData),
				       .EN_dataPorts_putIptData(multSwitches_7$EN_dataPorts_putIptData),
				       .EN_dataPorts_getPSum(multSwitches_7$EN_dataPorts_getPSum),
				       .EN_controlPorts_putNewConfig(multSwitches_7$EN_controlPorts_putNewConfig),
				       .RDY_dataPorts_putIptData(multSwitches_7$RDY_dataPorts_putIptData),
				       .dataPorts_getPSum(multSwitches_7$dataPorts_getPSum),
				       .RDY_dataPorts_getPSum(multSwitches_7$RDY_dataPorts_getPSum),
				       .RDY_controlPorts_putNewConfig(multSwitches_7$RDY_controlPorts_putNewConfig));

  // submodule multSwitches_0
  assign multSwitches_0$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[19:0] ;
  assign multSwitches_0$dataPorts_putIptData_newIptData =
	     dataPorts_0_putData_data ;
  assign multSwitches_0$EN_dataPorts_putIptData = EN_dataPorts_0_putData ;
  assign multSwitches_0$EN_dataPorts_getPSum = EN_dataPorts_0_getData ;
  assign multSwitches_0$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches != 32'd0 ;

  // submodule multSwitches_1
  assign multSwitches_1$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[39:20] ;
  assign multSwitches_1$dataPorts_putIptData_newIptData =
	     dataPorts_1_putData_data ;
  assign multSwitches_1$EN_dataPorts_putIptData = EN_dataPorts_1_putData ;
  assign multSwitches_1$EN_dataPorts_getPSum = EN_dataPorts_1_getData ;
  assign multSwitches_1$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd1 ;

  // submodule multSwitches_2
  assign multSwitches_2$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[59:40] ;
  assign multSwitches_2$dataPorts_putIptData_newIptData =
	     dataPorts_2_putData_data ;
  assign multSwitches_2$EN_dataPorts_putIptData = EN_dataPorts_2_putData ;
  assign multSwitches_2$EN_dataPorts_getPSum = EN_dataPorts_2_getData ;
  assign multSwitches_2$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd2 ;

  // submodule multSwitches_3
  assign multSwitches_3$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[79:60] ;
  assign multSwitches_3$dataPorts_putIptData_newIptData =
	     dataPorts_3_putData_data ;
  assign multSwitches_3$EN_dataPorts_putIptData = EN_dataPorts_3_putData ;
  assign multSwitches_3$EN_dataPorts_getPSum = EN_dataPorts_3_getData ;
  assign multSwitches_3$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd3 ;

  // submodule multSwitches_4
  assign multSwitches_4$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[99:80] ;
  assign multSwitches_4$dataPorts_putIptData_newIptData =
	     dataPorts_4_putData_data ;
  assign multSwitches_4$EN_dataPorts_putIptData = EN_dataPorts_4_putData ;
  assign multSwitches_4$EN_dataPorts_getPSum = EN_dataPorts_4_getData ;
  assign multSwitches_4$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd4 ;

  // submodule multSwitches_5
  assign multSwitches_5$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[119:100] ;
  assign multSwitches_5$dataPorts_putIptData_newIptData =
	     dataPorts_5_putData_data ;
  assign multSwitches_5$EN_dataPorts_putIptData = EN_dataPorts_5_putData ;
  assign multSwitches_5$EN_dataPorts_getPSum = EN_dataPorts_5_getData ;
  assign multSwitches_5$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd5 ;

  // submodule multSwitches_6
  assign multSwitches_6$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[139:120] ;
  assign multSwitches_6$dataPorts_putIptData_newIptData =
	     dataPorts_6_putData_data ;
  assign multSwitches_6$EN_dataPorts_putIptData = EN_dataPorts_6_putData ;
  assign multSwitches_6$EN_dataPorts_getPSum = EN_dataPorts_6_getData ;
  assign multSwitches_6$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd6 ;

  // submodule multSwitches_7
  assign multSwitches_7$controlPorts_putNewConfig_newConfig =
	     controlPorts_putConfig_newConfig[159:140] ;
  assign multSwitches_7$dataPorts_putIptData_newIptData =
	     dataPorts_7_putData_data ;
  assign multSwitches_7$EN_dataPorts_putIptData = EN_dataPorts_7_putData ;
  assign multSwitches_7$EN_dataPorts_getPSum = EN_dataPorts_7_getData ;
  assign multSwitches_7$EN_controlPorts_putNewConfig =
	     EN_controlPorts_putConfig &&
	     controlPorts_putConfig_numActualActiveMultSwitches > 32'd7 ;

  // remaining internal signals
  assign multSwitches_2_RDY_controlPorts_putNewConfig___ETC___d38 =
	     multSwitches_2$RDY_controlPorts_putNewConfig &&
	     multSwitches_3$RDY_controlPorts_putNewConfig &&
	     multSwitches_4$RDY_controlPorts_putNewConfig &&
	     multSwitches_5$RDY_controlPorts_putNewConfig &&
	     multSwitches_6$RDY_controlPorts_putNewConfig &&
	     multSwitches_7$RDY_controlPorts_putNewConfig &&
	     multSwitches_0$RDY_controlPorts_putNewConfig ;
endmodule  // mkMN_MultiplierNetwork

module mkMN_MultiplierSwitch (
    input wire CLK,
    input wire RST_N,
    
    input wire [15:0] dataPorts_putIptData_newIptData,
    input wire EN_dataPorts_putIptData,
    output wire RDY_dataPorts_putIptData,
    
    output wire [15:0] dataPorts_getPSum,
    input wire EN_dataPorts_getPSum,
    output wire RDY_dataPorts_getPSum,
    
    input wire [19:0] controlPorts_putNewConfig_newConfig,
    input wire EN_controlPorts_putNewConfig,
    output wire RDY_controlPorts_putNewConfig
);

    localparam [3:0] STATE_IDLE = 4'b0000;
    localparam [3:0] STATE_FILL_STATIONARY = 4'b0001;
    localparam [3:0] STATE_MULT_STREAMING = 4'b0010;
    
    reg [3:0] current_state;
    reg [15:0] psum_counter;
    reg [15:0] stationary_value;
    reg [31:0] mult_result;
    reg result_valid;
    
    wire [3:0] config_state = controlPorts_putNewConfig_newConfig[19:16];
    wire [15:0] config_psum = controlPorts_putNewConfig_newConfig[15:0];
    
    assign RDY_dataPorts_putIptData = 1'b1;
    assign RDY_dataPorts_getPSum = result_valid;
    assign RDY_controlPorts_putNewConfig = 1'b1;
    assign dataPorts_getPSum = mult_result[15:0];
    
    always @(posedge CLK or negedge RST_N) begin
        if (!RST_N) begin
            current_state <= STATE_IDLE;
            psum_counter <= 16'b0;
            stationary_value <= 16'b0;
            mult_result <= 32'b0;
            result_valid <= 1'b0;
        end 
        else begin
            
            // Clear valid when result is read
            if (EN_dataPorts_getPSum && result_valid) begin
                result_valid <= 1'b0;
            end
            
            // Handle configuration
            if (EN_controlPorts_putNewConfig) begin
                current_state <= config_state;
                psum_counter <= config_psum;
                result_valid <= 1'b0;
            end
            
            // State machine
            case (current_state)
            
                STATE_IDLE: begin
                end
                
                STATE_FILL_STATIONARY: begin
                    if (EN_dataPorts_putIptData) begin
                        stationary_value <= dataPorts_putIptData_newIptData;
                    end
                end
                
                STATE_MULT_STREAMING: begin
                    if (EN_dataPorts_putIptData && psum_counter > 0) begin
                        mult_result <= stationary_value * dataPorts_putIptData_newIptData;
                        result_valid <= 1'b1;
                        psum_counter <= psum_counter - 1;
                    end
                end
                
            endcase
        end
    end

endmodule